project_id = "ufuhxlroshwrpbdwgubd"

[functions.suggest-ideas]
verify_jwt = true

[functions.send-reminder-email]
verify_jwt = true

[functions.generate-survey]
verify_jwt = true

[functions.survey-response-notification]
verify_jwt = false

[functions.analyze-survey]
verify_jwt = true
